### ISSUE TITLE
Some adjustments

### ISSUE THREAD

**Issue by NC-MXTC** [mike-angek96/NCTaskManager#1]
This line and similar can be replaced with `return !this.isRepetitive`
https://github.com/mike-angek96/NCTaskManager/blob/cbef65750df438ab78a6b35134edb0b171f90255/src/main/java/mx/edu/j2se/liborio/tasks/Task.java#L46

This line and similar can be replaced with `return this.isRepetitive ? this.start : this.time;`
https://github.com/mike-angek96/NCTaskManager/blob/cbef65750df438ab78a6b35134edb0b171f90255/src/main/java/mx/edu/j2se/liborio/tasks/Task.java#L63

This line can be replaced with simply `return this.isRepetitive;`
https://github.com/mike-angek96/NCTaskManager/blob/cbef65750df438ab78a6b35134edb0b171f90255/src/main/java/mx/edu/j2se/liborio/tasks/Task.java#L87

Don't forget take into consideration active status for the task
https://github.com/mike-angek96/NCTaskManager/blob/cbef65750df438ab78a6b35134edb0b171f90255/src/main/java/mx/edu/j2se/liborio/tasks/Task.java#L94

Take into consideration the value of current for the next execution of non-repetitive tasks
https://github.com/mike-angek96/NCTaskManager/blob/cbef65750df438ab78a6b35134edb0b171f90255/src/main/java/mx/edu/j2se/liborio/tasks/Task.java#L98

**Comment by mike-angel-dev** [comment]
Solved 💯
